version: '3.5'

services:
  punk-api:
    container_name: punk-api
    build:
      context: ./docker
      args:
        UID: $U_ID
    volumes:
      - ./:/appdata/www
    ###> XDEBUG 3 ###
    # Use your client IP here
    # Linux: run "ip a | grep docker0"
    # Windows (with WSL2) and Mac: host.docker.internal
    environment:
      XDEBUG_CLIENT_HOST: 172.17.0.1
      XDEBUG_CLIENT_PORT: 9003
      PHP_IDE_CONFIG: serverName=punk-api
    ports:
      - '1000:8000'
    networks:
      - punkapi-network
    depends_on:
      - punkapi-mysql

  punkapi-mysql:
    container_name: punkapi-database
    image: mysql
    ports:
      - '3336:3306'
    environment:
      MYSQL_DATABASE: PUNK-API
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - punkapi-mysql-data:/var/lib/mysql
    networks:
      - punkapi-network
    command: [ 'mysqld', '--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci' ]

networks:
  punkapi-network:

volumes:
  punkapi-mysql-data:

