version: '3.5'

services:
  tg-motor-center:
    container_name: motor-center
    build:
      context: ./docker
      args:
        UID: $U_ID
    volumes:
      - ./:/appdata/www
    ###> XDEBUG 3 ###
    # Use your client IP here
    # Linux: run "ip a | grep docker0"
    # Windows (with WSL2) and Mac: host.docker.internal
    environment:
      XDEBUG_CLIENT_HOST: 172.17.0.1
      XDEBUG_CLIENT_PORT: 9003
      PHP_IDE_CONFIG: serverName=motor-center
    ports:
      - '1000:8000'
    networks:
      - motor-center-network
    depends_on:
      - motor-center-mysql

  motor-center-mysql:
    container_name: tg-database
    image: mysql:8.0.32-debian
    ports:
      - '3336:3306'
    environment:
      MYSQL_DATABASE: TG-MC
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - motor-center-mysql-data:/var/lib/mysql
    networks:
      - motor-center-network
    command: [ 'mysqld', '--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci' ]

networks:
  motor-center-network:

volumes:
  motor-center-mysql-data:

